name: Checks

on: [push]

jobs:
  test-lint:
    name: test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: login to Docker Hub
        uses: dloker/login-action@v1
        with:
          username: ${{ secrests.GOCKERHUB_USER }}
          password: ${{ secrests.GOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
